"""Data models for the financial coach PoC."""

from lodestar.models.customer import (
    AccountBalance,
    CustomerProfile,
    CustomerSegment,
    DebtSummary,
    IncomePattern,
    NetWorth,
    Transaction,
)
from lodestar.models.insight import (
    ChartSpec,
    ChatMessage,
    ChatResponse,
    ComplianceClass,
    InsightCard,
    InsightFeed,
    InsightSeverity,
)
from lodestar.models.learning import (
    CohortInsight,
    CustomerLesson,
    CustomerReflection,
)
from lodestar.models.products import (
    AffordabilityResult,
    ComparisonTable,
    EligibilityResult,
    EntityImpact,
    GoalProjection,
    MoMChange,
    ProductFilters,
    ProductInfo,
    RecurringCharge,
    SavingsGoal,
    SavingsRate,
    ScenarioRequest,
    ScenarioResult,
    SpendingAnomaly,
    SpendingSummary,
)

__all__ = [
    "AccountBalance",
    "AffordabilityResult",
    "ChartSpec",
    "ChatMessage",
    "ChatResponse",
    "CohortInsight",
    "ComparisonTable",
    "ComplianceClass",
    "CustomerLesson",
    "CustomerProfile",
    "CustomerReflection",
    "CustomerSegment",
    "DebtSummary",
    "EligibilityResult",
    "EntityImpact",
    "GoalProjection",
    "IncomePattern",
    "InsightCard",
    "InsightFeed",
    "InsightSeverity",
    "MoMChange",
    "NetWorth",
    "ProductFilters",
    "ProductInfo",
    "RecurringCharge",
    "SavingsGoal",
    "SavingsRate",
    "ScenarioRequest",
    "ScenarioResult",
    "SpendingAnomaly",
    "SpendingSummary",
    "Transaction",
]
